### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by jnsleeb** [infanf/pebble-abfahrten#4]
Hi,
The app doesn’t seem to be working for me. If i open it on my pebble it only shows fetching location and nearby stops but doesnt show any actual stops

**Comment by infanf** [comment]
Hi @jnsleeb 
I'd be surprised if it still worked to be honest. The app hasn't been maintained for over five years and it relies on scraping the MVV website. It might have to do with their internal coordinate system (which is not lat/lon). Maybe they changed it.
Feel free to fork and fix the app and publish it (if that is still possible). As I do not own/use a pebble watch anymore I won't continue development.
